name: Build Languager apk for LSPosed
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildapp signapp --upgrade && buildapp_fetch_tools

      - name: Build APK
        run: bash ./gradlew assembleRelease

      - name: Sign apk
        run: signapp -a app/build/outputs/apk/release/app-release-unsigned.apk -o app-release.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: languager-apk
          path: app-release.apk
